{% set version = "0.13.1" %}

package:
  name: curlylint
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/curlylint/curlylint-{{ version }}.tar.gz
  sha256: 008b9d160f3920404ac12efb05c0a39e209cb972f9aafd956b79c5f4e2162752

build:
  entry_points:
    - curlylint=curlylint.cli:patched_main
  script:
    - sed -i 's/parsy==/parsy>=/' setup.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  build:
    - sed
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - parsy >=1.1.0
    - attrs >=17.2.0
    - click >=6.5
    - toml >=0.9.4
    - pathspec >=0.6,<1

test:
  imports:
    - curlylint
  commands:
    - pip check
    - curlylint --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/thibaudcolas/curlylint
  summary: Experimental HTML templates linting for Jinja, Nunjucks, Django templates, Twig, Liquid
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
